#!/usr/bin/env bash

namespace=166248964328.dkr.ecr.us-east-1.amazonaws.com
repository=cimg-clojure
parent=openjdk
variants=(node browsers)
parentTags=(8.0 11.0 17.0 21.0)
defaultParentTag=21.0
parentSlug=openjdk
