#!/usr/bin/env bash

namespace=166248964328.dkr.ecr.eu-west-1.amazonaws.com
repository=cimg-clojure
parent=openjdk
variants=(node browsers)
parentTags=(8.0 11.0 17.0)
defaultParentTag=17.0
parentSlug=openjdk
